# Generated by Django 5.1.3 on 2024-11-19 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Militar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('patente', models.CharField(max_length=50)),
                ('id_mil', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViaturaAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=7, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViaturaOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=20)),
                ('eb_placa', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('destino', models.CharField(max_length=200)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acesso', models.CharField(choices=[('MILITAR', 'Militar'), ('VTR_ADM', 'Viatura Administrativa'), ('VTR_OP', 'Viatura Operacional'), ('VISITANTE', 'Visitante')], max_length=10)),
                ('data_hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.CharField(max_length=255)),
                ('odometro', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('chefe_viatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_como_chefe', to='access_control_app.militar')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_como_motorista', to='access_control_app.militar')),
                ('viatura_administrativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control_app.viaturaadministrativa')),
                ('viatura_operacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control_app.viaturaoperacional')),
            ],
        ),
    ]
