# Generated by Django 5.1.3 on 2024-11-20 15:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroacesso',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='registroacesso',
            name='viatura_administrativa',
        ),
        migrations.RemoveField(
            model_name='registroacesso',
            name='viatura_operacional',
        ),
        migrations.AlterField(
            model_name='militar',
            name='qr_code',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='qr_code',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
