# Generated by Django 5.1.3 on 2024-11-20 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control_app', '0002_remove_registroacesso_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacesso',
            name='militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_acesso_militar', to='access_control_app.militar'),
        ),
        migrations.AddField(
            model_name='registroacesso',
            name='visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_acesso_visitante', to='access_control_app.visitante'),
        ),
    ]
