# Generated by Django 5.1.3 on 2024-11-20 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control_app', '0003_registroacesso_militar_registroacesso_visitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacesso',
            name='viatura_administrativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_viatura_adm', to='access_control_app.viaturaadministrativa'),
        ),
        migrations.AddField(
            model_name='registroacesso',
            name='viatura_operacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_viatura_op', to='access_control_app.viaturaoperacional'),
        ),
    ]
