# Generated by Django 5.1.3 on 2024-11-21 03:47

import access_control_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control_app', '0005_militar_foto_visitante_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militar',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=access_control_app.models.upload_to, validators=[access_control_app.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=access_control_app.models.upload_to, validators=[access_control_app.models.validate_image]),
        ),
    ]
