# Generated by Django 5.1.3 on 2024-11-21 16:45

import uuid
from django.db import migrations, models


def generate_unique_qr_codes(apps, schema_editor):
    ViaturaAdministrativa = apps.get_model('access_control_app', 'ViaturaAdministrativa')
    ViaturaOperacional = apps.get_model('access_control_app', 'ViaturaOperacional')

    for viatura in ViaturaAdministrativa.objects.all():
        viatura.qr_code = uuid.uuid4()
        viatura.save(update_fields=['qr_code'])

    for viatura in ViaturaOperacional.objects.all():
        viatura.qr_code = uuid.uuid4()
        viatura.save(update_fields=['qr_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('access_control_app', '0007_viaturaadministrativa_dentro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaturaadministrativa',
            name='qr_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='viaturaoperacional',
            name='qr_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.RunPython(generate_unique_qr_codes),
    ]
