# Generated by Django 5.1.3 on 2024-11-21 16:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control_app', '0008_alter_viaturaadministrativa_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaturaadministrativa',
            name='qr_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='viaturaoperacional',
            name='qr_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
