# Generated by Django 5.1.3 on 2024-11-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control_app', '0009_alter_viaturaadministrativa_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='militar',
            name='dentro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitante',
            name='dentro',
            field=models.BooleanField(default=False),
        ),
    ]
