# Generated by Django 5.1.3 on 2024-11-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control_app', '0010_militar_dentro_visitante_dentro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroacesso',
            name='data_hora_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
